TAB_LANDSCAPE:
  WIDTH: '1024'
  HEIGHT: '768'

TAB_PORTRAIT:
 WIDTH: '768'
 HEIGHT: '1024'

MOB_LANDSCAPE:
 WIDTH: '640'
 HEIGHT: '360'

MOB_PORTRAIT:
 WIDTH: '360'
 HEIGHT: '640'

WEB:
 WIDTH: '1740'
 HEIGHT: '1024'

13INCH:
 WIDTH: '1366'
 HEIGHT: '768'